defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

run_mode: "eval"
save_filetypes: "vtk,np"

network_dir: 'checkpoints'
initialization_network_dir: 'checkpoints'

scheduler:
  decay_rate: 0.95
  decay_steps: 15000

training:
  rec_results_freq : 200
  rec_constraint_freq: 50000
  max_steps : 1500000

batch_size:
  inlet: 650
  outlet: 650
  no_slip: 5200
  interior: 6000
  integral_continuity: 310